In [ ]:
# СПОЧАТКУ ТРЕБА РОЗАРХІВУВАТИ datasets.7z!!!!!!!!

In [1]:
import pandas as pd
import numpy as np
import scipy.optimize as optimize
import math

data = pd.read_csv("books/books_data.csv")

# Ознайомлення з даними
print(data.head())
print(data.info())

                                               Title  \
0                     Its Only Art If Its Well Hung!   
1                           Dr. Seuss: American Icon   
2              Wonderful Worship in Smaller Churches   
3                      Whispers of the Wicked Saints   
4  Nation Dance: Religion, Identity and Cultural ...   

                                         description              authors  \
0                                                NaN     ['Julie Strain']   
1  Philip Nel takes a fascinating look into the k...       ['Philip Nel']   
2  This resource includes twelve principles in un...     ['David R. Ray']   
3  Julia Thomas finds her life spinning out of co...  ['Veronica Haddon']   
4                                                NaN      ['Edward Long']   

                                               image  \
0  http://books.google.com/books/content?id=DykPA...   
1  http://books.google.com/books/content?id=IjvHQ...   
2  http://books.google.com/books

In [2]:
unique_categories = data["categories"].unique()
category_counts = data["categories"].value_counts()

print("Унікальні категорії:", unique_categories)
print("Кількість книг у кожній категорії:", category_counts)

Унікальні категорії: ["['Comics & Graphic Novels']" "['Biography & Autobiography']"
 "['Religion']" ... "['Portsmouth Island (N.C.)']" "['Tobacco']"
 "['Flame in the wind (Motion picture)']"]
Кількість книг у кожній категорії: categories
['Fiction']                               23419
['Religion']                               9459
['History']                                9330
['Juvenile Fiction']                       6643
['Biography & Autobiography']              6324
                                          ...  
['Authors, Japanese']                         1
['Birth certificates']                        1
['Restaurant management']                     1
['Oxford (England)']                          1
['Flame in the wind (Motion picture)']        1
Name: count, Length: 10883, dtype: int64


In [3]:
unique_authors = data["authors"].unique()
author_counts = data["authors"].value_counts()

print("Унікальні автори:", unique_authors)
print("Кількість книг, написаних кожним автором:", author_counts)

Унікальні автори: ["['Julie Strain']" "['Philip Nel']" "['David R. Ray']" ...
 "['Daniel Banach', 'Travis Jones']" "['Wild Wild Cabbage']"
 "['David B. Johnson', 'Thomas A. Mowry']"]
Кількість книг, написаних кожним автором: authors
['Rose Arny']                                                                                                                   236
['William Shakespeare']                                                                                                         191
['Library of Congress. Copyright Office']                                                                                       178
['Agatha Christie']                                                                                                             142
['Erle Stanley Gardner']                                                                                                        124
                                                                                                           

In [4]:
unique_publishers = data["publisher"].unique()
publisher_counts = data["publisher"].value_counts()

print("Унікальні видавці:", unique_publishers)
print("Кількість ним видавцем:", publisher_counts)

Унікальні видавці: [nan 'A&C Black' 'iUniverse' ... 'Intelligent Consulting'
 'Devine Destinies' 'Strategic Wealth Solutions, LLC']
Кількість ним видавцем: publisher
Simon and Schuster                 3454
Penguin                            2825
Routledge                          2394
John Wiley & Sons                  2031
Harper Collins                     1911
                                   ... 
Amer Assn for Vocational              1
Blue Gem Publishing                   1
Brotherhood of Life Books             1
Frazer Press                          1
Strategic Wealth Solutions, LLC       1
Name: count, Length: 16016, dtype: int64


In [5]:
# Завантаження даних Steam Video Game Sales
sales_data = pd.read_csv("sales/vgsales.csv")
# Ознайомлення з даними
print(data.head())
print(data.info())

                                               Title  \
0                     Its Only Art If Its Well Hung!   
1                           Dr. Seuss: American Icon   
2              Wonderful Worship in Smaller Churches   
3                      Whispers of the Wicked Saints   
4  Nation Dance: Religion, Identity and Cultural ...   

                                         description              authors  \
0                                                NaN     ['Julie Strain']   
1  Philip Nel takes a fascinating look into the k...       ['Philip Nel']   
2  This resource includes twelve principles in un...     ['David R. Ray']   
3  Julia Thomas finds her life spinning out of co...  ['Veronica Haddon']   
4                                                NaN      ['Edward Long']   

                                               image  \
0  http://books.google.com/books/content?id=DykPA...   
1  http://books.google.com/books/content?id=IjvHQ...   
2  http://books.google.com/books

In [6]:
# Завантаження даних Video Game Completion Time
time_data_all_completions = pd.read_csv("time/all-completions.csv")
time_data_all_games_processed = pd.read_csv("time/all-games-processed.csv")
time_data_completions = pd.read_csv("time/completions.csv")
time_data_games = pd.read_csv("time/games.csv")
# Ознайомлення з даними
print(data.head())
print(data.info())

                                               Title  \
0                     Its Only Art If Its Well Hung!   
1                           Dr. Seuss: American Icon   
2              Wonderful Worship in Smaller Churches   
3                      Whispers of the Wicked Saints   
4  Nation Dance: Religion, Identity and Cultural ...   

                                         description              authors  \
0                                                NaN     ['Julie Strain']   
1  Philip Nel takes a fascinating look into the k...       ['Philip Nel']   
2  This resource includes twelve principles in un...     ['David R. Ray']   
3  Julia Thomas finds her life spinning out of co...  ['Veronica Haddon']   
4                                                NaN      ['Edward Long']   

                                               image  \
0  http://books.google.com/books/content?id=DykPA...   
1  http://books.google.com/books/content?id=IjvHQ...   
2  http://books.google.com/books

In [7]:
# Створення спільного ключа - назви гри
sales_data["Game Name"] = sales_data["Name"].apply(lambda x: x.lower())
time_data_games["Lowercase Title"] = time_data_games["title"].apply(lambda x: x.lower())

# Об'єднання таблиць
merged_data = pd.merge(sales_data, time_data_games, left_on="Game Name", right_on="Lowercase Title", how="inner")

# Видалення допоміжних стовпців
del merged_data["Game Name"]
del merged_data["Lowercase Title"]
print(merged_data.head())

   Rank               Name Platform    Year     Genre Publisher  NA_Sales  \
0     1         Wii Sports      Wii  2006.0    Sports  Nintendo     41.49   
1     2  Super Mario Bros.      NES  1985.0  Platform  Nintendo     29.08   
2     3     Mario Kart Wii      Wii  2008.0    Racing  Nintendo     15.85   
3     4  Wii Sports Resort      Wii  2009.0    Sports  Nintendo     15.75   
4     6             Tetris       GB  1989.0    Puzzle  Nintendo     23.20   

   EU_Sales  JP_Sales  Other_Sales  ...  coop  versus type  \
0     29.02      3.77         8.46  ...  17.5    12.5  NaN   
1      3.58      6.81         0.77  ...   NaN     NaN  NaN   
2     12.88      3.79         3.31  ...   NaN     NaN  NaN   
3     11.01      3.28         2.96  ...   NaN     NaN  NaN   
4      2.26      4.22         0.58  ...   NaN     NaN  NaN   

                                          developers  publishers  \
0                                       Nintendo EAD    Nintendo   
1                       Nint

In [8]:
avg_price_by_genre = merged_data.groupby("Genre")["Global_Sales"].mean()
print(avg_price_by_genre)

Genre
Action          0.631951
Adventure       0.332328
Fighting        0.609464
Misc            0.825337
Platform        1.097251
Puzzle          0.550218
Racing          0.693482
Role-Playing    0.604491
Shooter         0.849876
Simulation      0.669516
Sports          0.771780
Strategy        0.291358
Name: Global_Sales, dtype: float64


In [9]:
filtered_data = merged_data[(merged_data["Year"] > 2015) & (merged_data["Global_Sales"] < 20)]
print(filtered_data)

       Rank                                 Name Platform    Year     Genre  \
182     222                              FIFA 17      PS4  2016.0    Sports   
223     272           Uncharted 4: A Thief's End      PS4  2016.0   Shooter   
287     352            Tom Clancy's The Division      PS4  2016.0   Shooter   
684     847            Tom Clancy's The Division     XOne  2016.0   Shooter   
831    1028                            Overwatch      PS4  2016.0   Shooter   
...     ...                                  ...      ...     ...       ...   
9672  16475  Azure Striker Gunvolt: Striker Pack      3DS  2016.0    Action   
9686  16533             Sébastien Loeb Rally Evo     XOne  2016.0    Racing   
9687  16534                        Hitman (2016)     XOne  2016.0    Action   
9700  16565                         Mighty No. 9     XOne  2016.0  Platform   
9705  16579                    Rugby Challenge 3     XOne  2016.0    Sports   

                        Publisher  NA_Sales  EU_Sal

In [10]:
high_completion_low_sales = merged_data[(merged_data["completionist"] > 100) & (merged_data["Global_Sales"] < 100000)]
print(high_completion_low_sales)

       Rank                         Name Platform    Year         Genre  \
9        11                   Nintendogs       DS  2005.0    Simulation   
20       29       Gran Turismo 3: A-Spec      PS2  2001.0        Racing   
29       40      Super Smash Bros. Brawl      Wii  2008.0      Fighting   
31       42  Animal Crossing: Wild World       DS  2005.0    Simulation   
36       48               Gran Turismo 4      PS2  2004.0        Racing   
...     ...                          ...      ...     ...           ...   
9440  15766       Divinity: Original Sin       PC  2014.0  Role-Playing   
9456  15805             Football Academy       DS  2009.0        Sports   
9526  16028             The Last Remnant       PC  2009.0  Role-Playing   
9605  16279                Assetto Corsa     XOne  2016.0        Racing   
9663  16453  Hyperdimension Neptunia mk2      PS3  2011.0        Action   

                        Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
9                  

In [11]:
# Порядковий номер студента
n = 28

# Розмір матриць
matrix_size = n + 2

# Створення матриць
matrix_A = np.random.randint(0, 10, size=(matrix_size, matrix_size))
matrix_B = np.random.randint(0, 10, size=(matrix_size, matrix_size))

print("Матриця A:")
print(matrix_A)

print("Матриця B:")
print(matrix_B)

Матриця A:
[[3 3 7 0 7 4 3 1 3 2 8 2 8 8 1 7 5 6 4 0 0 2 6 8 1 0 5 4 6 3]
 [8 2 3 7 0 7 4 1 6 7 3 1 4 2 8 3 3 8 6 5 2 6 8 5 2 9 1 9 5 3]
 [8 7 6 7 2 4 5 2 7 5 5 0 7 1 5 9 6 5 3 5 5 1 0 6 9 7 4 6 4 4]
 [1 9 1 6 1 5 3 6 2 9 4 8 7 0 5 0 4 6 2 0 3 6 7 4 9 8 6 0 7 6]
 [8 7 6 9 9 2 1 2 9 8 9 1 4 7 7 1 5 5 7 2 0 1 7 2 2 5 2 9 3 9]
 [3 0 5 3 3 0 8 5 6 3 8 3 3 2 6 6 9 4 2 7 5 6 6 3 5 6 6 5 5 2]
 [1 3 0 6 6 6 5 9 0 9 8 4 6 1 2 6 8 7 3 7 4 9 3 2 1 8 2 1 9 4]
 [4 7 1 7 9 1 0 2 0 1 2 9 0 0 5 4 3 0 2 5 0 1 1 2 8 1 1 8 7 2]
 [7 0 1 1 9 0 5 6 1 8 9 8 4 1 0 9 8 7 6 2 3 9 0 2 4 4 5 6 2 9]
 [5 2 3 2 8 7 7 6 8 3 4 4 5 4 7 3 0 6 3 5 7 9 1 1 6 9 9 0 8 0]
 [9 9 0 2 7 5 3 1 0 1 0 3 1 2 8 1 3 7 8 9 5 1 0 3 6 2 6 2 1 6]
 [8 6 2 9 2 7 2 3 6 4 2 5 6 1 6 3 6 5 6 6 9 7 1 7 8 6 7 0 7 6]
 [8 0 9 1 9 9 1 3 6 1 4 2 6 3 9 1 6 8 8 3 3 9 9 6 5 0 4 0 6 3]
 [1 6 1 0 2 4 3 8 1 5 0 0 7 6 7 2 9 2 6 4 6 7 0 2 8 4 8 1 1 1]
 [5 1 4 8 1 4 2 8 8 9 1 0 9 9 3 7 0 7 5 4 4 0 8 8 9 5 9 1 5 0]
 [0 6 0 1 3 3 1 1 9 3 9 0 6 0 4 3 1 6 8 6 1 

In [12]:
# Додавання
matrix_sum = matrix_A + matrix_B
print("Сума матриць:")
print(matrix_sum)

# Віднімання
matrix_diff = matrix_A - matrix_B
print("Різниця матриць:")
print(matrix_diff)

# Ділення
# Заміна ділення на 0 на 1
matrix_div = matrix_A / matrix_B
matrix_div[matrix_div == np.inf] = 1  # Заміна NaN на 1
print("Ділення матриць:")
print(matrix_div)

Сума матриць:
[[ 8 10 10  9 14  9  8  8  7  6  8  4  9 17  9 11  9  7 11  6  0  8  8 12
   3  9 13  4 14  5]
 [14  2  7 16  0  9 13  8 12 15  4  1  6  4 10  6  9  9 12  9  4  9  9  8
   8 13  1 13 14  5]
 [13 14  9  9 10 10 10  8 15 10  8  8 13  5 12 17  7 10 10 10 14  9  8 14
  17 15  6 15  9  7]
 [ 2 10  2 11  6 11 12  6 10 15  7  9 13  7  6  3  7 13 11  6  6 11  8  7
  16 11  9  7 10  7]
 [ 8 10  6 18 18  2  2 10 11 15  9  4  5 10  7  1  8 13  9  5  4  4 14  6
   8 13  3 16 12  9]
 [11  1  6  3  9  4 10 13  9 10  8 10  7  3 11 10 18 10 11 14 13 13  7  3
   6 12  7 13 10  4]
 [ 6 10  4 15 12  6 12 16  4 15 15  4  6  6  8 13 10 12  5  7  7 12  3  8
   6 13  4  4  9 10]
 [ 9  9  6 16 17 10  0  9  4  4  7 11  9  1 12 13  6  7  7 13  0  5  9  7
  10  7  1 12 15  4]
 [12  2  5  7 13  4  7 15  2 17 11  8 10  4  3 14 10 14  6 11  6 17  6  9
   5 11 11  9  4 12]
 [ 8  7 12  5  8 16  8 12 12 12 11 12 11  4 11  6  2 12  4  6 13 17  1  3
  12 11 11  3 15  6]
 [18 17  0  6  8 14  4 10  5  4  3  

C:\Users\strog\AppData\Local\Temp\ipykernel_99552\4277134245.py:13: RuntimeWarning: divide by zero encountered in divide
  matrix_div = matrix_A / matrix_B
C:\Users\strog\AppData\Local\Temp\ipykernel_99552\4277134245.py:13: RuntimeWarning: invalid value encountered in divide
  matrix_div = matrix_A / matrix_B


In [13]:
# Скалярне множення
scalar = 5
matrix_scalar_mult = scalar * matrix_A
print("Скалярне множення на", scalar, ":")
print(matrix_scalar_mult)

# Векторне множення
matrix_vector_mult = matrix_A @ matrix_B
print("Векторне множення:")
print(matrix_vector_mult)

Скалярне множення на 5 :
[[15 15 35  0 35 20 15  5 15 10 40 10 40 40  5 35 25 30 20  0  0 10 30 40
   5  0 25 20 30 15]
 [40 10 15 35  0 35 20  5 30 35 15  5 20 10 40 15 15 40 30 25 10 30 40 25
  10 45  5 45 25 15]
 [40 35 30 35 10 20 25 10 35 25 25  0 35  5 25 45 30 25 15 25 25  5  0 30
  45 35 20 30 20 20]
 [ 5 45  5 30  5 25 15 30 10 45 20 40 35  0 25  0 20 30 10  0 15 30 35 20
  45 40 30  0 35 30]
 [40 35 30 45 45 10  5 10 45 40 45  5 20 35 35  5 25 25 35 10  0  5 35 10
  10 25 10 45 15 45]
 [15  0 25 15 15  0 40 25 30 15 40 15 15 10 30 30 45 20 10 35 25 30 30 15
  25 30 30 25 25 10]
 [ 5 15  0 30 30 30 25 45  0 45 40 20 30  5 10 30 40 35 15 35 20 45 15 10
   5 40 10  5 45 20]
 [20 35  5 35 45  5  0 10  0  5 10 45  0  0 25 20 15  0 10 25  0  5  5 10
  40  5  5 40 35 10]
 [35  0  5  5 45  0 25 30  5 40 45 40 20  5  0 45 40 35 30 10 15 45  0 10
  20 20 25 30 10 45]
 [25 10 15 10 40 35 35 30 40 15 20 20 25 20 35 15  0 30 15 25 35 45  5  5
  30 45 45  0 40  0]
 [45 45  0 10 35 25 15  5

In [14]:
# Визначник
matrix_det = np.linalg.det(matrix_A)
print("Визначник матриці A:", matrix_det)

# Власні числа
matrix_eigvals, matrix_eigvecs = np.linalg.eig(matrix_A)
print("Власні числа матриці A:")
print(matrix_eigvals)

print("Власні вектори матриці A:")
print(matrix_eigvecs)

Визначник матриці A: 1.4909498760282996e+31
Власні числа матриці A:
[134.35350316 +0.j         -12.31554103+10.69159381j
 -12.31554103-10.69159381j  13.53545932 +7.85772315j
  13.53545932 -7.85772315j  -2.10743161+12.81747991j
  -2.10743161-12.81747991j  13.72870517 +2.73234697j
  13.72870517 -2.73234697j  11.85767325 +0.j
   9.8021363  +6.33271824j   9.8021363  -6.33271824j
   7.89706729 +7.6454547j    7.89706729 -7.6454547j
   3.4102156  +8.90231147j   3.4102156  -8.90231147j
   7.18738621 +0.j         -10.61882477 +6.57989983j
 -10.61882477 -6.57989983j -10.40761292 +3.97088278j
 -10.40761292 -3.97088278j  -1.60068916 +8.9538817j
  -1.60068916 -8.9538817j   -3.71969365 +7.24678726j
  -3.71969365 -7.24678726j  -7.55660581 +1.85572105j
  -7.55660581 -1.85572105j  -3.59759951 +3.20952631j
  -3.59759951 -3.20952631j   2.70226695 +0.j        ]
Власні вектори матриці A:
[[-1.59206262e-01+0.00000000e+00j -1.75160088e-01+2.50519993e-02j
  -1.75160088e-01-2.50519993e-02j -2.18716492e-01+1.21

In [15]:
# Задана точка для обчислення похідної
x_point = np.pi / 5

# Визначення похідної
def f_derivative(x):
    return 2 / (1 + 4 * x**2) + 5 / (1 + x**2) - 1 / x

# Обчислення похідної в заданій точці
derivative = f_derivative(x_point)
print("Похідна в точці", x_point, ":", derivative)

Похідна в точці 0.6283185307179586 : 2.7686878441838383


In [16]:
# Заданий проміжок інтегрування
a = -2 * np.pi
b = 2 * np.pi

# Визначення первісної
def f_integral(x):
    return 2 * np.arctan(2 * x) + 5 * np.arctan(x) + np.log(np.abs(x))

# Обчислення первісної на заданому проміжку
integral = f_integral(b) - f_integral(a)
print("Первісна на проміжку [", a, ";", b, "]:", integral)

Первісна на проміжку [ -6.283185307179586 ; 6.283185307179586 ]: 20.095196151581234


In [17]:
# Визначення функції для оптимізації
def f_optimize(x):
    return math.atan(2 * x) + 5 * math.atan(x) - np.log(np.abs(x))  # Заміна arcctg на math.atan

# Знаходження глобального мінімуму
global_min_result = optimize.minimize(f_optimize, x0=0, method="Nelder-Mead")
global_min_x = global_min_result.x[0]
global_min_y = f_optimize(global_min_x)

print("Глобальний мінімум:", global_min_x, global_min_y)

# Знаходження локального мінімуму
local_min_result = optimize.minimize(f_optimize, x0=0.5, method="BFGS")
local_min_x = local_min_result.x[0]
local_min_y = f_optimize(local_min_x)

print("Локальний мінімум:", local_min_x, local_min_y)

Глобальний мінімум: 0.14862500000000012 2.9329855462234464
Локальний мінімум: -119564.13994436682 -21.11634020265347


C:\Users\strog\AppData\Local\Temp\ipykernel_99552\2685808610.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return math.atan(2 * x) + 5 * math.atan(x) - np.log(np.abs(x))  # Заміна arcctg на math.atan
C:\Users\strog\AppData\Local\Temp\ipykernel_99552\2685808610.py:3: RuntimeWarning: divide by zero encountered in log
  return math.atan(2 * x) + 5 * math.atan(x) - np.log(np.abs(x))  # Заміна arcctg на math.atan


In [18]:
# Порядковий номер студента
n = 28

# Розмір масиву
array_size = n + 1

# Створення масиву з мітками
array_labels = np.random.choice(["мітка" + str(i) for i in range(array_size)], size=array_size)
array_data = np.random.randint(0, 10, size=array_size)

array_series = pd.Series(data=array_data, index=array_labels)

print("Одномірний масив з мітками:")
print(array_series)

Одномірний масив з мітками:
мітка11    6
мітка22    0
мітка3     3
мітка9     5
мітка24    1
мітка27    0
мітка28    6
мітка20    0
мітка24    4
мітка20    1
мітка18    7
мітка15    3
мітка28    1
мітка0     2
мітка10    5
мітка15    7
мітка20    3
мітка3     7
мітка12    3
мітка21    6
мітка6     3
мітка4     7
мітка17    3
мітка22    4
мітка26    5
мітка24    7
мітка13    2
мітка13    3
мітка20    5
dtype: int32


In [19]:
# Створення словника
array_dict = {}
for i in range(array_size):
    array_dict[array_labels[i]] = array_data[i]

print("Словник:")
print(array_dict)

Словник:
{'мітка11': 6, 'мітка22': 4, 'мітка3': 7, 'мітка9': 5, 'мітка24': 7, 'мітка27': 0, 'мітка28': 1, 'мітка20': 5, 'мітка18': 7, 'мітка15': 7, 'мітка0': 2, 'мітка10': 5, 'мітка12': 3, 'мітка21': 6, 'мітка6': 3, 'мітка4': 7, 'мітка17': 3, 'мітка26': 5, 'мітка13': 3}


In [20]:
# Перевірити тип даних
print("Тип даних:", array_series.dtype)

# Додати

Тип даних: int32
